#include "onnx_frontend.h"
#include <cstring>
#include <fstream>
#include <map>
#include "onnx.pb.h"   // generated by: protoc --cpp_out=. onnx.proto

namespace dlc {

static std::vector<float> tensorData(const onnx::TensorProto& t) {
    std::vector<float> out;
    if (t.data_type() != onnx::TensorProto::FLOAT) return out;   // FP32 only for now
    if (!t.raw_data().empty()) {
        out.resize(t.raw_data().size() / sizeof(float));
        std::memcpy(out.data(), t.raw_data().data(), t.raw_data().size());
    } else {
        out.assign(t.float_data().begin(), t.float_data().end());
    }
    return out;
}

bool loadOnnx(const std::string& path, Graph& g, std::string& error) {
    onnx::ModelProto model;
    std::ifstream in(path, std::ios::binary);
    if (!in || !model.ParseFromIstream(&in)) { error = "cannot parse " + path; return false; }
    const auto& og = model.graph();

    std::map<std::string, int> ids;   // ONNX tensor name -> our value id

    for (const auto& init : og.initializer()) {              // weights and biases
        std::vector<int> shape(init.dims().begin(), init.dims().end());
        int id = g.addValue(init.name(), shape, true);
        g.values[id].data = tensorData(init);
        ids[init.name()] = id;
    }
    for (const auto& vi : og.input()) {                      // real inputs only
        if (ids.count(vi.name())) continue;                  // older exporters list weights here too
        std::vector<int> shape;
        for (const auto& d : vi.type().tensor_type().shape().dim())
            shape.push_back(d.has_dim_value() ? (int)d.dim_value() : -1);
        int id = g.addValue(vi.name(), shape);
        ids[vi.name()] = id;
        g.inputs.push_back(id);
    }
    for (const auto& n : og.node()) {
        std::vector<int> ins;
        for (const auto& name : n.input()) {
            if (!ids.count(name)) { error = "unknown tensor " + name; return false; }
            ins.push_back(ids[name]);
        }
        int out = g.addValue(n.output(0), {});               // shapes: add shape inference later
        ids[n.output(0)] = out;
        std::map<std::string, int> attrs;
        for (const auto& a : n.attribute())
            if (a.type() == onnx::AttributeProto::INT) attrs[a.name()] = (int)a.i();
        g.addOp(n.op_type(), ins, out, attrs);
    }
    for (const auto& o : og.output()) g.outputs.push_back(ids[o.name()]);
    return true;
}

}  // namespace dlc
